Address panic on closing a previously closed channel
blevesearch/bleve pull request #1613
Opened 2021-08-05 21:44 UTC by abhinavdangeti

Fixes: https://github.com/blevesearch/bleve/issues/1609

panic: close of closed channel

goroutine 68 [running]:
github.com/blevesearch/bleve/v2/index/scorch.(*closeChWrapper).close(0xc000346b80)
	/Users/runner/work/bleve/bleve/index/scorch/merge.go:228 +0x99
github.com/blevesearch/bleve/v2/index/scorch.(*closeChWrapper).listen(0xc000346b80)
	/Users/runner/work/bleve/bleve/index/scorch/merge.go:235 +0x1cd
created by github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).planMergeAtSnapshot
	/Users/runner/work/bleve/bleve/index/scorch/merge.go:275 +0x4ba

2021-08-06 03:56 UTC, sreekanth-cb requested changes
@abhinavdangeti , I don't understand the fix here as I see certain functionality getting removed.

For eg: now there is no way to cancel a force merge operation as the listen() function does nothing other than just waiting on certain events?

Also, note that the issue wasn't happening with a concurrent force merge and scorch close operation. 

Let's sync on later in a call. (maybe there is something in your fix which I am overlooking)

2021-08-06 04:44 UTC, abhinavdangeti commented
Ah I see. Ok so, will need to edit this fix. The panic occurs whenever the index is closed when force merge is in flight or if the operation is canceled - and then the defer cw.close() runs.

2021-08-06 14:40 UTC, mschoch requested changes
I recommend you fix the design instead.

2021-08-06 14:43 UTC, abhinavdangeti commented
> I recommend you fix the design instead.

Ya but sreekanth pointed out that I didn't take into account that there needs to be a way to cancel a running operation. So we'll need to support closing of this channel from a couple of places.

2021-08-06 15:15 UTC, mschoch commented
I need to review how it's used further, but this is more along the lines of what I was thinking...

2021-08-06 16:18 UTC, mschoch reviewed
OK, I thought adding another channel was going to be the solution, but having read through things more, I'm not not sure this is right either.  Maybe we'll have to meet on Monday...

2021-08-06 16:36 UTC, mschoch commented
Latest thought, why is this needed?

```
defer cw.close()
```

2021-08-06 16:40 UTC, abhinavdangeti commented
```
defer cw.close()
```

The defer is needed to close the listen() go routine.

2021-08-06 16:50 UTC, mschoch commented
Got it, so now I think I understand your solution.  Allow me to paraphrase and see if you agree:

The problem was that we shared the closeCh with 2 purposes, one to serve as indicator downstream to stop early (triggered by either ch1 or the context doneness) and also with ending the listen goroutine.

This current PR at the time I'm writing this, splits these into two separate channels.  This allows the outer defer-close to cleanup the listen goroutine, independently of channel we passed downstream as a signal.

@abhinavdangeti  Does the align with your thinking?

2021-08-06 16:52 UTC, abhinavdangeti commented
@mschoch That's accurate, yes.

2021-08-06 16:58 UTC, mschoch approved these changes

2021-08-06 16:58 UTC, mschoch commented
Approved, but would like Sreekanth's thoughts as well.  To me this is a better solution than refcouting our close calls, but I suppose it could be debatable...

2021-08-07 03:05 UTC, sreekanth-cb approved these changes
Looks good.

2021-08-09 15:28 UTC, merged