Introduce `NewKeywordFieldMapping()`.
blevesearch/bleve pull request #1636
Opened 2021-11-01 05:23 UTC by iredmail

A keyword field mapping is a text field with `keyword` analyzer.

2021-11-01 15:37 UTC, abhinavdangeti requested changes

2021-11-01 15:37 UTC, abhinavdangeti commented on mapping.go
> +// NewKeywordFieldMapping returns a default field mapping for text
This comment needs an update.

2021-11-01 20:38 UTC, abhinavdangeti commented on mapping.go
> +// NewKeywordFieldMapping returns a default field mapping for text
.. that this will only be applicable for textual fields.

2021-11-02 00:51 UTC, iredmail commented
@abhinavdangeti Updated the comment lines, could you help review again? Thanks. :)

2021-11-02 00:59 UTC, abhinavdangeti commented on mapping.go
> +// instead).
Sorry, but I don't like this verbiage either.
Prefer to keep it simple as ..

    NewKeywordFieldMapping returns a field mapping for text using the keyword
    analyzer, which essentially doesn't apply any specific text analysis.

2021-11-02 01:01 UTC, iredmail commented
Updated. :)

2021-11-02 15:05 UTC, abhinavdangeti approved these changes

2021-11-02 15:05 UTC, merged