Avoid double counting when sorting by field for faceted query
blevesearch/bleve pull request #1836
Opened 2023-07-06 04:28 UTC by metonymic-smokey

When a query sorts by the same field as the facets, the number of search results per field doubles. This is since there is double counting by the collector of the documents on that field for both sorting and faceting.

This PR deduplicates the fields in the collector to avoid this.

2023-07-06 09:05 UTC, Thejas-bhat approved these changes

2023-07-06 12:54 UTC, abhinavdangeti requested changes
Let's add a unit test test for this - the issue should be be easily reproduced.
Also create an MB for this and let's use it in the commit header.

2023-07-10 14:46 UTC, metonymic-smokey commented
Verification re the unit test:
Without the changes, the unit test fails with the following message:
```
aditiahuja@Aditis-MacBook-Pro collector % sudo go test --run=TestSetFacetsBuilder
--- FAIL: TestSetFacetsBuilder (0.00s)
    topn_test.go:768: expected fields in collector: [locations], observed: [locations locations]
FAIL
exit status 1
FAIL    github.com/blevesearch/bleve/v2/search/collector        0.558s

```

2023-07-10 16:02 UTC, abhinavdangeti commented on search/collector/topn_test.go
> +func TestSetFacetsBuilder(t *testing.T) {
Good test case, would you add an full index and search test case in search_test.go as well ..

- create an index
- add a few documents with doc values etc.
- search request with sort and facets
- make sure facet counts are accurate

2023-07-11 17:06 UTC, abhinavdangeti approved these changes
Well done.

2023-07-12 03:26 UTC, metonymic-smokey commented
Verification without change:
```
--- FAIL: TestSortedFacetedQuery (0.56s)
    search_test.go:114: expected 2, got 4
    search_test.go:114: expected 1, got 2
FAIL
exit status 1
FAIL    github.com/blevesearch/bleve/v2 1.799s
```

2023-07-12 03:28 UTC, merged