MB-27696: Allow a unique ID to be set for a Search Request
blevesearch/bleve pull request #1858
Opened 2023-07-26 11:11 UTC by CascadingRadium

## Jira

[MB-27696](https://issues.couchbase.com/browse/MB-27696)

## Description
Add a unique ID for a bleve Search Request which will be echo'd back in the Search Result. Would be useful in a parallel search query scenario to differentiate between the queries.

2023-07-26 17:39 UTC, abhinavdangeti requested changes

2023-07-26 17:39 UTC, abhinavdangeti commented on search.go
> +	ClientContextID  string            `json:"client_context_id"`
Allow for `omitempty`

2023-07-26 17:39 UTC, abhinavdangeti commented on search.go
> +		ClientContextID: search.NewUUID(),
Let's not do this by default here.

In bleve's purview it should remain something that's exclusively set by the client. So for couchbase, cbft will be responsible for generating a UUID if and only if the user does not already provide one and some config is enabled requiring us to generate for every request.

2023-07-27 14:27 UTC, abhinavdangeti approved these changes

2023-09-07 16:51 UTC, abhinavdangeti approved these changes

2023-09-08 07:41 UTC, Thejas-bhat approved these changes

2023-09-08 07:43 UTC, merged