MB-57973: Validate custom date time parser layout
blevesearch/bleve pull request #1859
Opened 2023-07-28 07:17 UTC by CascadingRadium

## Jira

[MB-57973](https://issues.couchbase.com/browse/MB-57973)

## Description
Currently user does not receive any feedback if the custom date time parser input by him is valid or not. These custom parsers must only contain magic numbers/ constants specified in https://pkg.go.dev/time#pkg-constants else it is not valid even though no error is returned buy the time package. The input validation here ensures only valid magic numbers are used.

2023-07-28 17:54 UTC, abhinavdangeti requested changes

2023-07-28 17:54 UTC, abhinavdangeti commented on analysis/datetime/flexible/flexible.go
> +	validMagicNumbers := map[string]bool{
map[string]struct{}{

2023-07-28 17:54 UTC, abhinavdangeti commented on analysis/datetime/flexible/flexible.go
> +	validMagicNumbers := map[string]bool{
Also let's initialize this construct globally as opposed to setting up a map on every call to validateLayout.

2023-07-28 17:54 UTC, abhinavdangeti commented on analysis/datetime/flexible/flexible.go
> +	re := regexp.MustCompile("[- :T,\\.<>;\\?!`~@#$%\\^&\\*|\\(\\){}\\[\\]/\\\\]")
Same for the regexp, move the initialization and all the common stuff to outside this method.

2023-07-28 17:54 UTC, abhinavdangeti commented on analysis/datetime/flexible/flexible.go
> +					" constants to use", layoutStr)
.. please refer to .. for supported layouts*.

2023-08-21 17:59 UTC, CascadingRadium commented on analysis/datetime/flexible/flexible.go
> +func validateLayout(layout string) bool {
ack

2023-08-21 18:27 UTC, abhinavdangeti approved these changes

2023-08-21 18:28 UTC, abhinavdangeti requested changes
Sorry - missed one comment in previous review. Would you add a couple of unit tests exercising the new code. Add a full stack unit test rather than just the datetime parsing, so perhaps in search_test.go.

2023-08-22 18:18 UTC, abhinavdangeti submitted a review, later dismissed

2023-08-24 15:21 UTC, abhinavdangeti commented
Let's drop this check, because of the pickle we can get into during an online upgrade if the layout defined was incorrect.

2023-08-29 14:29 UTC, abhinavdangeti reviewed
Re-considering this change because the failure in the upgrade paths (if the user was using invalid layouts before) is similar to a situation when the user created and used an analyzer component called `xy` and then upgraded to a version where we introduced a stock component `xy` - we'd see a similar validation/unmarshal error.

2023-08-29 14:39 UTC, abhinavdangeti approved these changes

2023-08-31 15:05 UTC, closed without merging

2023-09-05 20:16 UTC, abhinavdangeti commented
Closed in favor of https://github.com/blevesearch/bleve/pull/1877