Adding scorer explanation
blevesearch/bleve pull request #1914
Opened 2023-11-20 09:06 UTC by metonymic-smokey

2023-11-20 21:07 UTC, abhinavdangeti approved these changes
Looks fine to me.
@metonymic-smokey would you add a sample snippet of the "explain score" output to the commit message here.

Also, I'm glad you've set the base branch to `MB-59102` so there'd be no conflicts, but I think we should merge this into unstable after the base PR has been so we don't squash this into it and create a separate commit entry for this.

2023-11-21 06:05 UTC, metonymic-smokey commented
Done, pls let me know what you think.
thanks!

2023-11-21 17:29 UTC, abhinavdangeti requested changes

2023-11-21 17:29 UTC, abhinavdangeti commented on search/scorer/scorer_knn.go
> +						sqs.queryField, sqs.queryVector, sqs.queryBoost, knnMatch.ID),
Just noticed this, let's not emit the actual query vector to the output - there'll be an overload of data.

2023-11-21 17:29 UTC, abhinavdangeti commented on search/scorer/scorer_knn.go
> +				sqs.queryField, sqs.queryVector, sqs.queryBoost),
Ditto.

2023-11-22 04:48 UTC, metonymic-smokey commented
Pls review this PR instead - https://github.com/blevesearch/bleve/pull/1899

2023-11-22 04:48 UTC, closed without merging