change score breakdown from array to map
blevesearch/bleve pull request #1921
Opened 2023-11-27 11:57 UTC by CascadingRadium

looking at https://issues.couchbase.com/browse/MB-59821
it seems that having score breakdown as a slice would be inoptimal in other use cases of disjunction searchers such as in Prefix and Wildcard queries. 
Here the number of searchers involved in a single disjunction searcher may be very large and can affect cpu execution time.
This approach changes the datatype of scorebreakdown to a map

2023-11-27 18:26 UTC, abhinavdangeti requested changes

2023-11-27 18:26 UTC, abhinavdangeti commented on search_knn.go
> +	scoreBreakdown []*map[int]float64
Does this need to be an array of maps?

Also the map does not need to be a pointer, just `[]map[int]float64` should do.

2023-11-27 18:26 UTC, abhinavdangeti commented on search/search.go
> +	ScoreBreakdown map[int]float64 `json:"score_breakdown,omitempty"`
Update the commentary above on what the key-values in this map represent.

2023-11-27 23:46 UTC, abhinavdangeti reviewed
@CascadingRadium I thought we spoke of determining the score breakdown and shipping it _only_ when a knn request comes in ? If you are doing that already, I can't quite seem to spot it - would you point me to it.

2023-11-28 06:27 UTC, CascadingRadium commented
yea but i wanted to check if the regressions go away with just the optimization in this PR. if the results arent so good, i will add that check, in a different PR.

2023-11-28 16:45 UTC, abhinavdangeti commented
Per conversation w/ @CascadingRadium - new patch coming here addressing above comments.

2023-11-29 16:54 UTC, abhinavdangeti requested changes
Our conversation was this -
* Ok to do a score breakdown when a compound query is involved.
* I wanted us to put in an optimization where we do optimize a compound query with kNN to simply a kNN when possible -
    * `match_none` OR single `kNN`
    * `match_all` AND single `kNN`
* It is ok to do a score breakdown for multi kNN

2023-11-29 16:54 UTC, abhinavdangeti commented on search/query/conjunction.go
> +	RetrieveScoreBreakdown bool    `json:"retrieve_score_breakdown,omitempty"`
Yo, I don't like the feel of this at all.

2023-12-01 00:08 UTC, abhinavdangeti approved these changes

2023-12-01 02:14 UTC, merged