MB-61640: Toy: Fuzzy and Wildcard dynamic scoring
blevesearch/bleve pull request #2056
Opened 2024-07-24 10:34 UTC by Likith101

- Added lavenshtein distance calculation for fuzzy and wildcard searchers
 - Added new implementations of certain functions to allow passing of edit distances per term
 - Multiplied boosts by inverse of edit distance for score calculation

2024-08-06 06:09 UTC, CascadingRadium requested changes

2024-08-06 06:09 UTC, CascadingRadium commented on search/searcher/search_fuzzy.go
> +	var reuse []int
i think this can be shifted to where it was

2024-08-06 06:09 UTC, CascadingRadium commented on search/searcher/search_fuzzy.go
> +	var reuse []int
line 139

2024-08-06 06:09 UTC, CascadingRadium commented on search/searcher/search_fuzzy.go
> +		boost, fuzzyCandidates.editDistances, options, true)
line 54 here indicates that `fuzzyCandidates` can be nil... so i think in line 57.5 you can add editDistances = fuzzyCandidates.editDistances there, just like candidates = fuzzyCandidates.candidates

2024-08-06 06:09 UTC, CascadingRadium commented on search/searcher/search_multi_term.go
> +func NewMultiTermSearcherBoosted(ctx context.Context, indexReader index.IndexReader, terms []string,
pls add a comment here regarding what this does

2024-08-06 06:54 UTC, CascadingRadium commented
also please add unit tests to show the effect (with and w/o boost) across match and match_phrase queries thanks

2024-11-18 15:13 UTC, CascadingRadium submitted a review, later dismissed

2024-11-20 17:11 UTC, abhinavdangeti approved these changes

2024-11-21 05:15 UTC, merged