use the thesaurus datatype to search for equivalent terms
blevesearch/bleve pull request #2090
Opened 2024-10-16 12:12 UTC by CascadingRadium

2024-12-05 05:53 UTC, metonymic-smokey commented on index_impl.go
> +	var fts search.FieldTermSynonymMap
Please change the name from "fts":)

2024-12-18 22:09 UTC, abhinavdangeti requested changes

2024-12-18 22:09 UTC, abhinavdangeti commented on search/util.go
> +			(*f)[field][term] = append((*f)[field][term], synonyms...)
Doesn't look very GO idiomatic at all, with the above change this can become `f[field][term]` ?

2024-12-18 22:09 UTC, abhinavdangeti commented on search/util.go
> +func (f *FieldTermSynonymMap) MergeWith(fts FieldTermSynonymMap) {
Can this not be ..

```
func (f FieldTermSynonymMap) MergeWith(..)
```

2024-12-18 22:09 UTC, abhinavdangeti commented on mapping/synonym.go
> +	CollectionName string `json:"collection"`
There is no notion of collection for a library user - I suppose you'll be adding a separate documentation on how the library users can benefit from.

2024-12-18 22:09 UTC, abhinavdangeti commented on analysis/type.go
> +	Collection() string
How does `Collection()` as a source translate to an independent library user?

2024-12-19 16:14 UTC, abhinavdangeti approved these changes

2024-12-19 16:14 UTC, abhinavdangeti commented
Thanks @CascadingRadium . Let's get this in for now and incrementally improve the area as and when needed.

2024-12-19 16:14 UTC, merged

2024-12-19 16:18 UTC, CascadingRadium commented
Thank you for merging @abhinavdangeti