Retrieve PartialMatch Only for Match Queries
blevesearch/bleve pull request #2103
Opened 2024-11-21 13:28 UTC by CascadingRadium

- Previously, we returned the PartialMatch field for every hit when the query 
  used a Disjunction Searcher. However, this behavior is incorrect, as the 
  PartialMatch attribute is only relevant for Match Queries.

2024-11-21 15:05 UTC, abhinavdangeti commented
So just so we're clear here - partial_match will be set if an explicit disjunction were used and all its components did not match yes?
And also separately, if a match query resolves to a disjunction - and if some of the components did not match, we'll now be setting partial_match - correct?

2024-11-21 15:32 UTC, CascadingRadium commented
- A match query will be a disjunction query over all the terms, here if the document has all 
  the terms then partial_match will be set to true else it will be set to false.
- For all other queries partial_match will never show up in the search result as its `omitempty` and will be simply excluded from the search result.

2024-11-21 15:37 UTC, abhinavdangeti commented
Ok, then I disagree with your proposal here - we should be returning a partial_match when a disjunction's component doesn't match as well.

2024-11-21 17:09 UTC, CascadingRadium commented
like in a disjunction query ?

2024-11-21 17:12 UTC, abhinavdangeti commented
> like when the top-most query is a disjunction query ?

Ya.

2025-01-10 17:05 UTC, abhinavdangeti requested changes
Per last conversation.

2025-01-16 10:29 UTC, CascadingRadium commented
Actually, this approach has the limitation with disjunction + match queries
like so 

```
{
  "disjuncts":[
    {
      "match":"termA termB",
    },
    {
      "match":"SONY PS5",
      "prefix_length":0,
      "fuzziness":1
    },
  ]
}
```

where a single PartialMatch in the searchResult would lead to confusion regarding which component was partially matched (matchQuery1 / matchQuery2 / outerDisjuncts)

i will propose a new solution where the partialMatch is reflected in the score explanation, where each subQuery's expl will have the partialMatch attribute

2025-02-03 21:05 UTC, abhinavdangeti approved these changes

2025-02-04 10:46 UTC, merged