MB-57888: WIP: Index Update
blevesearch/bleve pull request #2106
Opened 2024-11-26 07:58 UTC by Likith101

2025-02-24 07:12 UTC, Thejas-bhat commented on index_update.go
> +	return fieldInfo, nil
@Likith101, let me know if the following understanding is correct.

To me it looks like we're doing multiple iterations over the two pairs of type mappings to first validate, then accumulate all the fields' information in both the type mappings as part of fieldInfo and then remove the ones which are identical.

This approach seems to have redundant work in it imo, like isn't it possible to do all this in a single iteration with a custom callback that defines the checking of the field mapping's info between the orig and updated ones and populate a fieldInfo map that's maintained in this function? 

Please let me know if the suggested thought is valid or not, thanks

2025-02-27 14:01 UTC, Likith101 commented on index_update.go
> +	return fieldInfo, nil
The multiple iterations of processing the two mappings were necessary. At each step, we eliminate a lot of possible edge cases and handling them all at once in the end is a huge task.

For example, the very first iteration, we simply check for mappings or fields that are present in the updated mapping which are not present in the original. This was done so that any future functions do not have to worry about the edge case where a mapping in updated does not have a corresponding one in the original.

Another case is where after adding every single field info, we validate with all of the existing ones to check if there are any corner cases like same path or same field alias while having different deleted information being hit. While this seems redundant, doing it all at the end was near impossible.

Code complexity wise, I don't believe we are doing too much redundant work overall. We do two passes of each mapping and then if there are n fields in updated mapping, we do n<sup>2</sup> checks with a map along with n proper field comparisons.

2025-02-28 05:30 UTC, Thejas-bhat commented on index/scorch/optimize_knn.go
> +						vecIndex, err = segment.InterpretVectorIndex("",
we can just short circuit the downstream operations by returning here right? like we know that an empty string field name is never going to exist in the index files and hence a backing faiss index won't be formed. so let's not perform calls to zap and keep it simple like

```
if info, ok := o.snapshot.updatedFields[field]; ok && (info.Deleted || info.Index) {
     return saying field doesn't exist
}
vecIndex, err := segment.InterpretVectorIndex(field,
		o.requiresFiltering, origSeg.deleted)
```

so we can just do a no-op or return an error saying "field doesn't exist"

2025-02-28 05:33 UTC, Thejas-bhat commented on index_update.go
> +	return fieldInfo, nil
hmm i see. cool let me try understanding this code a little better as well, thanks

2025-02-28 05:33 UTC, Thejas-bhat commented on index_update.go
> +
small nit: could you please remove these new lines (i see a bunch of them) just so that we are consistent with the other functions' structure

2025-03-07 09:18 UTC, CascadingRadium commented
hi @Likith101 can you please rebase over master and fix conflicts

2025-03-07 10:38 UTC, CascadingRadium commented on index_impl.go
> +		if rck == "updated_mapping" {
`updated_mapping` is a cross-reference term; it is set within cbft.
set a bleve global variable 
`const UpdatedMappingKey = "updated_mapping"`
and reference `bleve.UpdatedMappingKey` in cbft

2025-03-10 13:47 UTC, CascadingRadium reviewed
first pass will continue

2025-03-11 06:25 UTC, Likith101 commented on index_impl.go
> +			if val, ok := rcv.(string); ok {
This seems a bit redundant. I believe the extra indent makes it easier to understand.

2025-03-11 06:27 UTC, Likith101 commented on index_impl.go
> +	err = rv.i.SetInternal(scorch.MappingInternalKey, mappingBytes)
Could you point out where in upside_down we are using this key? I am unable to find it.

2025-03-12 14:36 UTC, CascadingRadium reviewed
second pass

2025-03-12 14:36 UTC, CascadingRadium commented on index_update.go
> +// Date time parsers in custom analysis but not in use are not compared
there is no comparison for `customDateTimeParsers`? refactor to how it is above for analyzers. Here you're checking for equality for built-in datetime parsers also which is not required.

```
oriDateTimeParsers := make(map[string]interface{})
updDateTimeParsers := make(map[string]interface{})

extractDateTimeParsers := func(paths map[string]PathInfo, customParsers map[string]interface{}, parsers map[string]interface{}, defaultParser string) {
	for _, info := range paths {
		for _, fInfo := range info.fieldMapInfo {
			if fInfo.fieldMapping.Type == "datetime" {
				dateTimeParserName := fInfo.fieldMapping.DateFormat
				if dateTimeParserName == "" {
					dateTimeParserName = defaultParser
				}
				fInfo.datetimeParser = dateTimeParserName
				if val, ok := customParsers[dateTimeParserName]; ok {
					parsers[dateTimeParserName] = val
				}
			}
		}
	}
}

extractDateTimeParsers(oriPaths, ori.CustomAnalysis.DateTimeParsers, oriDateTimeParsers, ori.DefaultDateTimeParser)
extractDateTimeParsers(updPaths, upd.CustomAnalysis.DateTimeParsers, updDateTimeParsers, upd.DefaultDateTimeParser)

```

2025-03-12 14:36 UTC, CascadingRadium commented on index_update.go
> +func compareSynonymSources(oriPaths, updPaths map[string]*pathInfo, ori, upd *mapping.IndexMappingImpl) error {
why checking for this differently to `analyzers` and `datetimeparsers`?
If you add / remove / modify any synonym source **NOT** being used by any field mapping, it should not rebuild but restart.

```
func compareSynonymSources( oriPaths, updPaths map[string]PathInfo, ori, upd *mapping.IndexMappingImpl) error {
	oriSynonymSources := make(map[string]interface{})
	updSynonymSources := make(map[string]interface{})

	extractSynonymSources := func(paths map[string]PathInfo, customSources map[string]interface{}, sources map[string]interface{}, getSynonymSourceName func(path string) string) {
		for path, info := range paths {
			for _, fInfo := range info.fieldMapInfo {
				if fInfo.fieldMapping.Type == "text" {
					synonymSourceName := getSynonymSourceName(path)
					fInfo.synonymSource = synonymSourceName
					if val, ok := customSources[synonymSourceName]; ok {
						sources[synonymSourceName] = val
					}
				}
			}
		}
	}

	extractSynonymSources(oriPaths, ori.CustomAnalysis.SynonymSources, oriSynonymSources, ori.SynonymSourceForPath)
	extractSynonymSources(updPaths, upd.CustomAnalysis.SynonymSources, updSynonymSources, upd.SynonymSourceForPath)

	for name, synUpd := range upd.CustomAnalysis.SynonymSources {
		if synOri, ok := ori.CustomAnalysis.SynonymSources[name]; ok {
			if !reflect.DeepEqual(synUpd, synOri) {
				return fmt.Errorf("synonym source %s changed while being used by fields", name)
			}
		} else {
			return fmt.Errorf("synonym source %s added to an existing field", name)
		}
	}

	return nil
}
```

2025-03-12 14:37 UTC, CascadingRadium commented on index_update.go
> +		addPathInfo(updPaths, "", updDMapping, ori, nil, name)
resolved

2025-03-12 15:49 UTC, CascadingRadium commented
theres one case which is not implemented.
consider the following scenario

1. OriginalMapping
```
   "analysis": {
    "analyzers": {
     "custAna": {
      "token_filters": [
       "custFilt"
      ],
      "type": "custom",
      "tokenizer": "unicode"
     }
    },
    "token_filters": {
     "custFilt": {
      "min": 3,
      "max": 255,
      "type": "length"
     }
    },
   "types": {
    "abc": {
     "enabled": true,
     "dynamic": true,
     "default_analyzer": "custAna"
    }
   }
   
```

2. UpdatedMapping
```
   "analysis": {
    "analyzers": {
     "custAna": {
      "token_filters": [
       "custFilt"
      ],
      "type": "custom",
      "tokenizer": "unicode"
     }
    },
    "token_filters": {
     "custFilt": {
      "min": 10,
      "max": 255,
      "type": "length"
     }
    },
   "types": {
    "abc": {
     "enabled": true,
     "dynamic": true,
     "default_analyzer": "custAna"
    }
   }
```

Here assume the `custAna` analyzer is used in a type_mapping. Now, although the custom analyzer has not changed and the type_mapping is the same, the custom analysis component used within the custom analyzer has changed. This check is not there and it can wrongly flag the update as successful.

2025-03-13 11:36 UTC, CascadingRadium commented on index_update.go
> +func compareFieldMapping(original, updated *mapping.FieldMapping) (*index.UpdateFieldInfo, bool, error) {
so the `compareFieldMapping` returns a `bool` flag that i feel is redundant.
the only usage of this updated is in L601
```
	if updated {
		if ori.dynamic {
			return fmt.Errorf("updated field is under a dynamic property")
		}
	}
```
you can just remove the bool return value and just return the  `UpdateFieldInfo` and `error`. You can just do the check in L601 instead
```
	if (newInfo.Deleted || newInfo.Index || newInfo.Store || newInfo.DocValues) && ori.dynamic {
	     return fmt.Errorf("updated field is under a dynamic property")
	}
```

2025-03-13 11:36 UTC, CascadingRadium commented on index_update.go
> +	if ori.DefaultField != upd.DefaultField {
L137 - L139 can be removed as this check is not required as unpdating `DefaultField` should not cause an index rebuild

2025-03-13 11:38 UTC, CascadingRadium commented on index_update.go
> +			return nil, false, nil
shouldn't this be 
```
return rv, false, nil
```
as downstream there is no check for the `UpdateFieldInfo` returned by this function being nil, which can cause a panic - in L607 for example

2025-03-13 11:47 UTC, CascadingRadium commented on index_update.go
> +			return nil, false, nil
actually seeing the code again in L239
```
	for _, fMap := range mp.Fields {
		fieldMapInfo := &fieldMapInfo{
			fieldMapping: fMap,
			rootName:     rootName,
			parent:       pInfo,
		}
		pInfo.fieldMapInfo = append(pInfo.fieldMapInfo, fieldMapInfo)
	}
```
so there can be no chance of original being nil as in L425 we are iterating through `ori.fieldMapInfo` which if it has a valid value, Must have a valid non-nil `fieldMapping` as per the L239

```
	if upd == nil {
		for _, oriFMapInfo := range ori.fieldMapInfo {
			info, updated, err = compareFieldMapping(oriFMapInfo.fieldMapping, nil)
			if err != nil {
				return err
			}
```

2025-03-13 12:32 UTC, CascadingRadium commented on index_update.go
> +			if updSynonymSource != "" && oriFMapInfo.synonymSource != updSynonymSource {
remove L465 - L467 as re previous comment, also remove `synonymSource` from struct in L41

2025-03-17 07:25 UTC, CascadingRadium submitted a review, later dismissed

2025-03-17 16:36 UTC, abhinavdangeti requested changes

2025-03-17 16:36 UTC, abhinavdangeti commented on index/scorch/scorch.go
> +var MappingInternalKey = []byte("_mapping")
Should make this a `const` - and I don't think this is the right place for this as @CascadingRadium commented earlier.

2025-03-17 16:36 UTC, abhinavdangeti commented on index_impl.go
> +	err = rv.i.SetInternal(scorch.MappingInternalKey, mappingBytes)
I agree with @CascadingRadium that we should not relocate this to within `index/scorch`.
That said, relocating this into `bleve_index_api` doesn't feel right either.

To avoid circular dependencies, let's move this alongside all other keys as well into a a key.go file within `index` - they all must be `const` and exported for their use everywhere.

2025-03-19 00:43 UTC, abhinavdangeti requested changes
Looking mostly ok to me @Likith101 - I've a few requests for some more commentary and the positioning the mapping_key and we should be good here.

2025-03-19 00:43 UTC, abhinavdangeti commented on index/scorch/optimize_knn.go
> +					if info, ok := o.snapshot.updatedFields[field]; ok && (info.Deleted || info.Index) {
As far as readability goes, I have to say this looks a bit off-putting, perhaps commentary here on why `|| info.Index` will help.

2025-03-19 00:43 UTC, abhinavdangeti commented on index/scorch/persister.go
> +  boltUpdatedFieldsKey          = []byte("fields")
Fix formatting here - think I'm responsible here while resolving conflicts.

2025-03-19 00:43 UTC, abhinavdangeti commented on index/scorch/snapshot_index.go
> +	updatedFields map[string]*index.UpdateFieldInfo
Let's add a lot of commentary around here indicating what this is for (for the future), and what each of the attributes of `UpdateFieldInfo` stand for.

2025-03-19 00:43 UTC, abhinavdangeti commented on index/scorch/snapshot_segment.go
> +
Drop empty line.

2025-03-19 00:43 UTC, abhinavdangeti commented on index_impl.go
> +	mappingBytes, err := indexReader.GetInternal(scorch.MappingInternalKey)
Relocate MappingInternalKey and other keys into a separate keys.go within `index/`.

2025-03-19 00:46 UTC, abhinavdangeti commented
@Likith101 Would you add a new `docs/index_update.md` with a title "Ability to reduce downtime during index mapping updates" (in the same format as the other docs there) indicating the status quo and capturing how to leverage this feature for our community users.

I'll leave it be your decision if you want to make that a separate commit, but it'll need to be available before we produce v2.5.0.

2025-03-20 05:17 UTC, Thejas-bhat commented on index_impl.go
> +	mappingBytes, err := indexReader.GetInternal(scorch.MappingInternalKey)
@abhinavdangeti, adding to what you've suggested here - creating a new file called keys.go under means that we'd need to define the package name for the file. Perhaps we can leverage the existing util package that exists at the bleve level? or maybe we can create a new util package within index/ (although that sounds redundant because its something applicable to all types of indexes)

2025-03-20 05:34 UTC, Likith101 commented on index_impl.go
> +	mappingBytes, err := indexReader.GetInternal(scorch.MappingInternalKey)
The only other keys are boltdb related keys from index/scorch/persister.go. There are other keys within the search package as well. Which of these keys should I move to keys.go.

Also, we would need a package for keys.go. Would it be within /index or do I need to make a new directory as well so that it would be /index/keys/keys.go? If it is the former, then what would the package name be?

2025-03-20 13:57 UTC, CascadingRadium commented on docs/index_update.md
> +* *v2.5.0* (and after) will come with support to delete certain fields or parts of the fields without requiring a full rebuild of the index
`delete or modify any field mapping in the index mapping`

2025-03-20 13:57 UTC, CascadingRadium commented on docs/index_update.md
> +While opening an index, if an updated mapping is provided as a string under the key `updated_mapping` within the `runtimeConfig` parameter of `openIndexUsing`, then we open the index and try to updat
`OpenUsing` as it is a `bleve` package exported method.
also simplify the english
```
If `updated_mapping` is provided as a string in the `runtimeConfig` parameter of `OpenUsing`, the index is opened and updated with the new mapping.
```

2025-03-20 13:57 UTC, CascadingRadium commented on docs/index_update.md
> +On failure, we still return a usable index with an error explaining why the update failed.
the old index with old mapping is returned, `usable` index is misleading 
```
If the update fails, the index is opened with the existing mapping, and an error is returned explaining why the update was unsuccessful.
```

2025-03-20 13:57 UTC, CascadingRadium commented on docs/index_update.md
> +    * Any changes to IncludeInAll, type, IncludeTermvECTORS AND SkipFreqNorm
Fix `IncludeTermvECTORS` typo

2025-03-20 13:57 UTC, CascadingRadium commented on docs/index_update.md
> +* Non updatable changes
I would suggest replacing `Non updatable changes` section with a `Updatable changes` section, as this would make it clear to the end-user about what functionality is supported, rather than what is not. 
This would make it clear to the user that any index mapping change which is not present in the `Updatable changes` section is by default not supported

2025-03-20 13:57 UTC, CascadingRadium commented on docs/index_update.md
> +
also add a Sample code here demonstrating the feature, from a Bleve standpoint, using the exported `bleve` package-level APIs

2025-03-20 15:51 UTC, abhinavdangeti commented on index_impl.go
> +	mappingBytes, err := indexReader.GetInternal(scorch.MappingInternalKey)
Good point @Thejas-bhat . @Likith101 let's do that - move into util/keys.go all the keys that are common the `scorch` and `upside_down`.

2025-03-20 19:40 UTC, abhinavdangeti commented on docs/index_update.md
> +While opening an index, if an updated mapping is provided as a string under the key `updated_mapping` within the `runtimeConfig` parameter of `openIndexUsing`, then we open the index and try to updat
Correct^, `openIndexUsing` is _not_ an exported API - so needs no mention here.

2025-03-20 19:41 UTC, abhinavdangeti commented on docs/index_update.md
> +While opening an index, if an updated mapping is provided as a string under the key `updated_mapping` within the `runtimeConfig` parameter of `openIndexUsing`, then we open the index and try to updat
Throw in an example here, showing that usecase.

2025-03-20 19:49 UTC, abhinavdangeti requested changes
@Likith101 It seems this is introducing multiple unit test failures that need your attention - _please_ make it a practice to run `go test ./...` locally with and without the `vectors` tag before proposing each patch.

2025-03-20 19:56 UTC, abhinavdangeti commented
.. and `go test ./... -race`.

2025-03-26 19:29 UTC, abhinavdangeti commented
Removed all traces of supporting code needed here with https://github.com/blevesearch/bleve/pull/2171, will need new PRs and linking those to this one.

2025-09-12 20:57 UTC, abhinavdangeti requested changes
A vector unit test requires attention ..
```
--- FAIL: TestIndexUpdateVector (0.07s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered, repanicked]
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x100381494]

goroutine 14502 [running]:
testing.tRunner.func1.2({0x1006bc4c0, 0x100b1ce80})
	/opt/homebrew/Cellar/go/1.25.0/libexec/src/testing/testing.go:1872 +0x190
testing.tRunner.func1()
	/opt/homebrew/Cellar/go/1.25.0/libexec/src/testing/testing.go:1875 +0x31c
panic({0x1006bc4c0?, 0x100b1ce80?})
	/opt/homebrew/Cellar/go/1.25.0/libexec/src/runtime/panic.go:783 +0x120
github.com/blevesearch/bleve/v2/index/scorch.(*IndexSnapshotVectorReader).Next(0x1400039ad00, 0x1?)
	/Users/abhinav.dangeti/Documents/go/src/github.com/blevesearch/bleve/index/scorch/snapshot_index_vr.go:86 +0x74
github.com/blevesearch/bleve/v2/search/searcher.(*KNNSearcher).Next(0x140007488c0, 0x14001b8cb40)
	/Users/abhinav.dangeti/Documents/go/src/github.com/blevesearch/bleve/search/searcher/search_knn.go:118 +0x94
github.com/blevesearch/bleve/v2/search/searcher.(*DisjunctionSliceSearcher).initSearchers(0x140000d66c0, 0x14001b8cb40)
	/Users/abhinav.dangeti/Documents/go/src/github.com/blevesearch/bleve/search/searcher/search_disjunction_slice.go:151 +0x9c
github.com/blevesearch/bleve/v2/search/searcher.(*DisjunctionSliceSearcher).Next(0x140000d66c0, 0x14001b8cb40)
	/Users/abhinav.dangeti/Documents/go/src/github.com/blevesearch/bleve/search/searcher/search_disjunction_slice.go:215 +0x30
github.com/blevesearch/bleve/v2/search/collector.(*KNNCollector).Collect(0x14000647a00, {0x10078e588, 0x100bde840}, {0x100793100, 0x140000d66c0}, {0x100794d68, 0x1400012e4d0})
	/Users/abhinav.dangeti/Documents/go/src/github.com/blevesearch/bleve/search/collector/knn.go:181 +0x264
github.com/blevesearch/bleve/v2.(*indexImpl).runKnnCollector(0x140001d2930, {0x10078e588, 0x100bde840}, 0x14000432f00, {0x100794d68, 0x1400012e4d0}, 0x0)
	/Users/abhinav.dangeti/Documents/go/src/github.com/blevesearch/bleve/search_knn.go:412 +0x354
github.com/blevesearch/bleve/v2.(*indexImpl).SearchInContext(0x140001d2930, {0x10078e588, 0x100bde840}, 0x14000432f00)
	/Users/abhinav.dangeti/Documents/go/src/github.com/blevesearch/bleve/index_impl.go:700 +0x6e0
github.com/blevesearch/bleve/v2.(*indexImpl).Search(0x0?, 0x48?)
	/Users/abhinav.dangeti/Documents/go/src/github.com/blevesearch/bleve/index_impl.go:480 +0x30
github.com/blevesearch/bleve/v2.TestIndexUpdateVector(0x14000910e00)
	/Users/abhinav.dangeti/Documents/go/src/github.com/blevesearch/bleve/search_knn_test.go:1904 +0x1c40
testing.tRunner(0x14000910e00, 0x1007843a8)
	/opt/homebrew/Cellar/go/1.25.0/libexec/src/testing/testing.go:1934 +0xc8
created by testing.(*T).Run in goroutine 1
	/opt/homebrew/Cellar/go/1.25.0/libexec/src/testing/testing.go:1997 +0x364
FAIL	github.com/blevesearch/bleve/v2	48.307s
```

2025-09-12 20:57 UTC, abhinavdangeti commented on util/keys.go
> +var (
Should change these to `const`s.

2025-09-17 18:05 UTC, abhinavdangeti commented on docs/index_update.md
> +* *v2.5.0* (and after) will come with support to delete or modify any field mapping in the index mapping without requiring a full rebuild of the index
v2.5.4

2025-09-17 18:05 UTC, abhinavdangeti commented on index/scorch/scorch.go
> +	if !s.loadedBolt {
Can a data race occur over this?

2025-09-18 13:35 UTC, Likith101 commented on util/keys.go
> +var (
Byte arrays cannot be constant. These variables were always var, so I left it the same way I found them.

They have to be byte arrays for their usage within bolt.

2025-09-18 13:38 UTC, Likith101 commented on index/scorch/scorch.go
> +	if !s.loadedBolt {
No, this is only used during the update path where bolt needs to be loaded before the index is started. The order of execution is always sequential, so I believe there is no risk of a data race here.

2025-09-18 14:00 UTC, abhinavdangeti commented on index/scorch/scorch.go
> +	if !s.loadedBolt {
Perhaps this check needs to be situated in `OpenMeta()` also then for readability and for safety as it's an exported API.

2025-09-18 14:00 UTC, abhinavdangeti commented on util/keys.go
> +var (
Ack.

2025-09-19 19:02 UTC, abhinavdangeti commented
Looking good, let me make one more pass early next week.

2025-09-25 15:14 UTC, abhinavdangeti commented on index/scorch/scorch.go
> +	s.root.m.Lock()
Let's not use `m` outside an IndexSnapshot member method - it doesn't seem like we call the IndexSnapshot method `UpdateFieldsInfo` outside lock context, so let's move the acquiring and releasing lock functionality to within it.

2025-10-06 14:51 UTC, CascadingRadium submitted a review, later dismissed

2025-10-06 17:55 UTC, abhinavdangeti submitted a review, later dismissed
@Likith101 one check required for `scoring_model` as well allowing any change between states - `"", "tf-idf", "bm25" to be changeable without index rebuild. Please weigh in on whether that change is required here or in cbft.

2025-10-06 20:56 UTC, Thejas-bhat commented on index/scorch/scorch.go
> +	loadedBolt               bool
given that `s.rootbolt` is pointed to the right instance within this function, it would suffice to use that as a nil check whether there's a bolt instance right? or do you see any scenario where that's not a sufficient check/might be brittle?

2025-10-06 20:56 UTC, Thejas-bhat commented on index_impl.go
> +		var ok bool
i don't think you need to define this, the := notation will pass through and the 211 check will be on a valid var.

2025-10-07 10:22 UTC, Likith101 commented on index_impl.go
> +		var ok bool
There is a check on line 264 that will fail if I define this inside the if statement

2025-10-08 05:40 UTC, Likith101 commented on index/scorch/scorch.go
> +	loadedBolt               bool
Agreed, I removed the variable and adjusted so that s.rootbolt is used everywhere instead

2025-10-08 14:45 UTC, abhinavdangeti commented on index_update.go
> +		if ori.ScoringModel != "" && ori.ScoringModel != "tf-idf" && ori.ScoringModel != "bm25" ||
There're constants in bleve_index_api for `tf-idf` and `bm25` which you should use here.

Also why check `ori.ScoringModel` here, just checking `upd.ScoringModel` should suffice yes?

2025-10-08 21:34 UTC, abhinavdangeti commented on index_update.go
> +		if ori.ScoringModel != "" && ori.ScoringModel != index.TFIDFScoring && ori.ScoringModel != index.BM25Scoring ||
As we discussed would you add detailed commentary around here on why we add these checks.

2025-10-09 08:45 UTC, CascadingRadium approved these changes

2025-10-09 13:50 UTC, abhinavdangeti approved these changes

2025-10-09 14:23 UTC, merged