WIP: BM25 scoring
blevesearch/bleve pull request #2113
Opened 2024-12-06 06:50 UTC by Thejas-bhat

2025-01-08 17:13 UTC, abhinavdangeti requested changes
@Thejas-bhat Make sure to pull the latest from `origin/bm25-refactor` before you push more commits here :)

2025-01-08 17:13 UTC, abhinavdangeti commented on mapping/index.go
> +	if _, ok := index.SupportedScoringModels[im.ScoringModel]; !ok {
You'll need a check here for the `empty` case.

2025-01-08 17:13 UTC, abhinavdangeti commented on search/searcher/search_term.go
> +				count, avgDocLength, err = bm25ScoreMetrics(ctx, field, indexReader)
Hmm it seems we'd be double calculating in the event of `bm25` scoring choice - perhaps an if-and-else is warranted here to either calculate just `tfTDFScoreMetrics` or `bm25ScoreMetrics`.

2025-01-08 17:13 UTC, abhinavdangeti commented on search/util.go
> +const SearcherEndCallbackKey = "_searcher_end_callback_key"
I realize this is older code, but just to resolve some tech-debt as well here - would you add some commentary to what each key here stands for.

2025-01-08 17:13 UTC, abhinavdangeti commented on search/util.go
> +const BM25MapKey = "_bm25_map_key"
ditto^

2025-01-08 17:13 UTC, abhinavdangeti commented on search/util.go
> +const GetScoringModelCallbackKey = "_get_scoring_model"
ditto^

Worth situating all these keys together perhaps too?

2025-01-09 22:11 UTC, abhinavdangeti commented
@Thejas-bhat a thought regarding the "global scoring" code path for bm25 - what is the default behavior in elastic?

Would you add a couple of GO benchmark test to differentiate between bm25 with and without global scoring and record these numbers within the commit message^ - trying to decide whether to enable "global scoring" by default.

2025-01-09 22:21 UTC, abhinavdangeti commented on search/searcher/search_term.go
> +				count, avgDocLength, err = bm25ScoreMetrics(ctx, field, indexReader)
👍🏼

2025-01-09 22:30 UTC, abhinavdangeti requested changes

2025-01-09 22:30 UTC, abhinavdangeti commented on search/scorer/scorer_term.go
> +var b float64 = 0.75
Like we discussed, no point in making these `var`s and keeping them unexported.
Perhaps export them and prefix a `BM25` to indicate what they're applicable to.

2025-01-09 22:30 UTC, abhinavdangeti commented on search/scorer/scorer_term.go
> +	docTerm uint64, avgDocLength float64, options search.SearcherOptions) *TermQueryScorer {
I realize `docTerm` is carry-over name, but perhaps we should replace all occurrences of it with something better indicative of what it exactly is.

2025-01-09 22:30 UTC, abhinavdangeti commented on search/searcher/search_term.go
> +	return count, float64(fieldCardinality / int(count)), nil
It seems the 2nd parameter is always 0 here, so why declare it even and do a divide by operation and then return it. Change return params to 0 and `avgDocLength` below where this method is referenced will remain at zero.

2025-01-09 22:30 UTC, abhinavdangeti commented on search/searcher/search_term.go
> +		count, avgDocLength, err = tfTDFScoreMetrics(indexReader)
No need for this 2nd parameter here at all, related to previous comment^.

2025-01-10 07:21 UTC, Thejas-bhat commented on search/scorer/scorer_term.go
> +	docTerm uint64, avgDocLength float64, options search.SearcherOptions) *TermQueryScorer {
maybe the name is self-explanatory (the alternate names i can think of is docFreq - number of documents having the term). it's just that the lack commentary makes it a little less obvious. shall i just add the commentary alongside docTerm in the struct and leave it as is?

2025-01-10 07:24 UTC, Thejas-bhat commented
> @Thejas-bhat a thought regarding the "global scoring" code path for bm25 - what is the default behavior in elastic?
> 
> Would you add a couple of GO benchmark test to differentiate between bm25 with and without global scoring and record these numbers within the commit message^ - trying to decide whether to enable "global scoring" by default.

By default, elastic disables the feature. It'll be a bit difficult to benchmark this at golang unit level over here, because the latency is mainly visible when the index alias has multiple shards and each of which is spread across multiple nodes.

2025-01-10 14:43 UTC, metonymic-smokey commented on search/scorer/scorer_term.go
> +			Message: fmt.Sprintf("saturation(term:%s), k1=%f/(tf=%f + k1*fieldNorm=%f))",
While I see that you've used BM25 specific terms like 'saturation' here, as you should, I think it would be good to add the scoring mode(tf-idf/BM25) too in the explanation?

2025-01-10 14:48 UTC, metonymic-smokey commented on search/searcher/search_term.go
> +	term []byte, field string, boost float64, options search.SearcherOptions) (search.Searcher, error) {
Nit: I think this extra line space can be removed.

2025-01-10 14:56 UTC, metonymic-smokey commented on search/util.go
> +var BM25_b float64 = 0.75
We can discuss this separately - how did you arrive at these defaults for b and k1? Could you pls add some commentary around that?

2025-01-10 15:28 UTC, abhinavdangeti commented on search/scorer/scorer_term.go
> +	docTerm uint64, avgDocLength float64, options search.SearcherOptions) *TermQueryScorer {
Roger, perhaps some commentary on all the function parameters then.

2025-01-13 04:51 UTC, Thejas-bhat commented on search/scorer/scorer_term.go
> +			Message: fmt.Sprintf("saturation(term:%s), k1=%f/(tf=%f + k1*fieldNorm=%f))",
done

2025-01-13 04:54 UTC, Thejas-bhat commented on search/util.go
> +var BM25_b float64 = 0.75
these are defaults as per elastic search docs. i've added links to the blog and docs as a code comment.

2025-01-13 04:56 UTC, Thejas-bhat commented on search/searcher/search_term.go
> +	term []byte, field string, boost float64, options search.SearcherOptions) (search.Searcher, error) {
i broke the line mainly because it'll be easy in the future while working on this area (so that all the params are fit within that 80 chars limit and we don't have to scroll much)

2025-01-13 17:43 UTC, abhinavdangeti reviewed
Minor refactor suggestion, looks good to me otherwise.

2025-01-13 17:43 UTC, abhinavdangeti commented on index_impl.go
> +	fieldCardinality := make(map[string]int)
Lets change this to ..
```
var fieldCardinality map[string]int
```

.. and `make` only if `isBM25Enabled(..) == true` in line 499 below.

2025-01-13 17:43 UTC, abhinavdangeti commented on index_impl.go
> +				skipKNNCollector = true
Is this right? Something we missed?

2025-01-13 17:43 UTC, abhinavdangeti commented on index_alias_impl.go
> +func isBM25Enabled(m mapping.IndexMapping) bool {
Let's refactor this to `scoringModel(..)` which returns the scoring model to use instead.

2025-01-13 17:43 UTC, abhinavdangeti commented on index_impl.go
> +		if isBM25Enabled(i.m) {
Related to other commend, let's update this method to return the scoring model to use.
To establish if it's bm25, you can add the extra check - `scoringModel() == index.BM25Scoring`.

2025-01-13 20:04 UTC, abhinavdangeti commented on index_alias_impl.go
> +func isBM25Enabled(m mapping.IndexMapping) bool {
On second thought, perhaps this is fine as is - given that IndexMappingImpl's ScoringModel is exported.

2025-01-13 20:06 UTC, abhinavdangeti commented on index_impl.go
> +		if isBM25Enabled(i.m) {
Perhaps this is also fine as is.

2025-01-13 20:07 UTC, abhinavdangeti reviewed
Can we also add a unit test comparing bm25 to tf-idf scoring over the same dataset?

2025-01-13 20:07 UTC, abhinavdangeti commented on index_test.go
> +func TestGlobalScoring(t *testing.T) {
Rename to `TestBM25GlobalScoring`

2025-01-14 14:13 UTC, Thejas-bhat commented on index_impl.go
> +				skipKNNCollector = true
yeah i've removed this, it seems like a merge conflict issue, thanks!

2025-01-14 14:16 UTC, Thejas-bhat commented
> Can we also add a unit test comparing bm25 to tf-idf scoring over the same dataset?

I've added a unit test on a sample 10 doc dataset, however i don't think there something concrete we can compare over there apart from tfidf scores being higher than bm25 (due to algo difference). a much better test would be to have a large enough dataset, and two indexes - one with bm25 and the other with tfidf and then compare the relevancy of the hits from each of them (https://www.elastic.co/blog/found-bm-vs-lucene-default-similarity)

2025-01-14 15:56 UTC, abhinavdangeti approved these changes

2025-01-15 09:08 UTC, merged